Upgrade dompdf to 2.0.0
ImpressCMS/impresscms pull request #1240
Opened 2022-07-27 06:42 UTC by fiammybe

security fix

2022-07-27 07:34 UTC, MekDrop approved these changes

2022-07-27 07:36 UTC, MekDrop requested changes
I approved and than I remembered that also `composer.lock` is here needed.

2022-08-03 06:37 UTC, fiammybe commented
I merged in the change that should automatically update the composer.lock, and then made some cosmetic changes to trigger a retest. Would that be enough to get the composer.lock up-to-date?

2022-08-03 06:38 UTC, fiammybe commented
Looks like it :-), I just now saw the new commit.

2022-08-03 07:24 UTC, MekDrop approved these changes

2022-08-03 07:24 UTC, merged