Templated form elements
ImpressCMS/impresscms pull request #1584
Opened 2024-10-22 12:49 UTC by fiammybe

CSS frameworks (Bulma, Bootstrap, Tailwind, ...) all need specific HTML markup for their form solution to work well. The HTML implementation in the core was not flexible enough to allow that. I started with a button, and will gradually transform all hardcoded HTML in the form elements to using templates. 
This should be transparent, unless you want to use a theme that redefines the form elements :-)

2025-02-07 07:07 UTC, MekDrop requested changes

2025-02-07 07:07 UTC, MekDrop commented on htdocs/libraries/icms/form/Element.php
> +	protected icms_view_Tpl $_tpl;
can we for new vars not use `_` prefix? it's doesn't make sense

2025-02-07 07:07 UTC, MekDrop commented on htdocs/libraries/icms/form/elements/Button.php
> +	$this->_tpl->assign('extra', $this->getExtra());
some formatting issue I think is here? somehow it's looks without indent

2025-02-07 20:18 UTC, fiammybe commented on htdocs/libraries/icms/form/Element.php
> +	protected icms_view_Tpl $_tpl;
I believe it was in the early PHP4 days a convention to show that it was a protected variable. You are right, it doesn't make any sense anymore and I'll change it.

2025-03-15 22:18 UTC, MekDrop approved these changes

2025-03-16 12:17 UTC, merged