Fixed #733: Rename using the proper naming convention (This is a public var)
ImpressCMS/impresscms pull request #736
Opened 2020-08-08 20:40 UTC by MekDrop

As title says. With backward compatibility.

2020-12-15 22:39 UTC, fiammybe approved these changes

2020-12-15 22:44 UTC, fiammybe requested changes
I think I broke something with the conflict resolution ...

2020-12-15 23:37 UTC, MekDrop commented
There was two `__get` functions in one class. I think that was that issue that prevented our tests to be completed. I fixed that.

2020-12-16 10:45 UTC, fiammybe approved these changes

2020-12-16 10:46 UTC, merged

2020-12-16 10:46 UTC, fiammybe commented
thanks for the fix, I overlooked that :-(